package mock

import core "go-coding-dojo/coffeequeue/core"
import mock "github.com/stretchr/testify/mock"

// IOrder is an autogenerated mock type for the IOrder type
type IOrder struct {
	mock.Mock
}

// GetCustomer provides a mock function with given fields:
func (_m *IOrder) GetCustomer() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetDelay provides a mock function with given fields:
func (_m *IOrder) GetDelay() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetName provides a mock function with given fields:
func (_m *IOrder) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

var _ core.IOrder = (*IOrder)(nil)
