package mock

import core "go-coding-dojo/coffeequeue/core"
import mock "github.com/stretchr/testify/mock"

// IQueue is an autogenerated mock type for the IQueue type
type IQueue struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *IQueue) Get() core.IOrder {
	ret := _m.Called()

	var r0 core.IOrder
	if rf, ok := ret.Get(0).(func() core.IOrder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.IOrder)
		}
	}

	return r0
}

// Put provides a mock function with given fields: _a0
func (_m *IQueue) Put(_a0 core.IOrder) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(core.IOrder) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

var _ core.IQueue = (*IQueue)(nil)
